version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - /home/jordan/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
